### ISSUE TITLE
Missing mime types

### ISSUE THREAD

**Issue by arvindsv** [gocd-contrib/gocd-oss-cookbooks#16]
Not entirely sure where to do this in this repo. So, opening an issue instead.

When `aws s3 sync` is used (as in [the documentation pipeline](https://build.gocd.org/go/tab/build/detail/gocd-docs.go.cd-master/166/PushToGHPages/1/pushtoghpages_job#tab-console)), it tries to [guess](https://docs.aws.amazon.com/cli/latest/reference/s3/sync.html) the mime-type to use for a file. This happens in aws-cli, [here](https://github.com/aws/aws-cli/blob/1.14.52/awscli/customizations/s3/utils.py#L294) for the version we have in `gocddev/gocd-dev-build:centos-6-v2.0.27`.

However, the file `/etc/mime.types` does not exist. So, this causes `aws s3 sync` to use a default content-type of `binary/octet-stream` for files such as SVG files, causing S3 to serve them as such. Browsers will refuse to display such SVG files.

```
$ python -c 'import mimetypes; print(mimetypes.knownfiles); print("\nMime type of test.svg is: " + str(mimetypes.guess_type("test.svg")[0]))'

['/etc/mime.types', '/etc/httpd/mime.types', '/etc/httpd/conf/mime.types', '/etc/apache/mime.types', '/etc/apache2/mime.types', '/usr/local/etc/httpd/conf/mime.types', '/usr/local/lib/netscape/mime.types', '/usr/local/etc/httpd/conf/mime.types', '/usr/local/etc/mime.types']

Mime type of test.svg is: None

$ sudo yum install -y mailcap
...

$ python -c 'import mimetypes; print(mimetypes.knownfiles); print("\nMime type of test.svg is: " + str(mimetypes.guess_type("test.svg")[0]))'

['/etc/mime.types', '/etc/httpd/mime.types', '/etc/httpd/conf/mime.types', '/etc/apache/mime.types', '/etc/apache2/mime.types', '/usr/local/etc/httpd/conf/mime.types', '/usr/local/lib/netscape/mime.types', '/usr/local/etc/httpd/conf/mime.types', '/usr/local/etc/mime.types']

Mime type of test.svg is: image/svg+xml
```

#### Summary:

We need to install the `mailcap` package, at least for the centos-6 and centos-7 images. Maybe it should be added somewhere [here](https://github.com/gocd-contrib/gocd-oss-cookbooks/blob/37039c1808a9934c4b67fa926571e0eddcd33939/custom-cookbooks/cloudcli-wrapper/recipes/default.rb)?

/cc @varshavaradarajan

**Comment by ketan** [comment]
I remember doing this before. Not sure what caused this to break.

**Comment by chadlwilson** [comment]
This was done in bcfa96b8 but a little moot possibly since the docs are pushed using GH actions now. :-)
